### ISSUE TITLE
Ukrainian language

### ISSUE THREAD

**Issue by Hester1337** [Stef-Moroyna/Spaceflight-Simulator-Translations#7]
Translation of Ukrainian
@Stef-Moroyna
[Ukrainian.txt](https://github.com/Stef-Moroyna/Spaceflight-Simulator-Translations/files/10135989/Ukrainian.txt)

**Comment by Hester1337** [comment]
Translation of Ukrainian
@Stef-Moroyna

**Comment by dani0105** [comment]
create a Pull request with the changes

**Comment by Hester1337** [comment]
> create a Pull request with the changes

did it
